# fly.toml app configuration file generated for my-rails-api

app = "my-rails-api"
primary_region = "nrt"

[build]

[deploy]
  release_command = "./bin/rails db:prepare"

[env]
  RAILS_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[statics]]
  guest_path = "/myapp/public"
  url_prefix = "/"
